version: "3.6"

services:
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"

  app:
    build: .
    volumes:
      - ./src/clubbable/clubbable/settings:/usr/src/clubbable/src/clubbable/clubbable/settings
      - ./src/clubbable/clubbable/db:/usr/src/clubbable/src/clubbable/clubbable/db
    links:
      - rabbit:rabbit

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src/clubbable/clubbable/static:/usr/share/nginx/html
    links:
      - app:app
