# Generated by Django 2.1.4 on 2018-12-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('date_of_listing', models.DateField()),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('admitted_to_club', models.BooleanField(default=False)),
                ('date_admitted', models.DateField(blank=True, null=True)),
                ('delisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('number_of_tables', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('initials', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('post_title', models.CharField(blank=True, max_length=100)),
                ('familiar_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('send_emails', models.BooleanField(default=False)),
                ('qualification_art', models.BooleanField(default=False)),
                ('qualification_drama', models.BooleanField(default=False)),
                ('qualification_literature', models.BooleanField(default=False)),
                ('qualification_music', models.BooleanField(default=False)),
                ('qualification_science', models.BooleanField(default=False)),
                ('hon_life_member', models.BooleanField(default=False, verbose_name='Honorary life member')),
                ('canonisation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'familiar_name'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
