# Generated by Django 2.2 on 2019-06-02 15:48

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20181226_1851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', club.models.EmailUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership_category',
            field=models.CharField(choices=[('O', 'Ordinary member'), ('Z', 'Former member'), ('E', 'External contact')], default='O', max_length=1),
        ),
    ]
