#!/bin/bash

rm -f clubbable-eb.zip
git archive --format=zip HEAD > clubbable-eb.zip
src/clubbable/manage.py collectstatic --noinput --settings clubbable.settings.production
zip -r clubbable-eb.zip src/clubbable/clubbable/static
zip -r clubbable-eb.zip src/clubbable/clubbable/settings
zip clubbable-eb.zip Dockerrun.aws.json
