#!/bin/bash

rm -f clubbable.tar.gz
git archive --format=tar.gz --prefix=clubbable/ HEAD > clubbable.tar.gz
docker build --tag=clubbable_app:latest .
docker tag clubbable_app:latest kaapstorm/clubbable:latest
docker push kaapstorm/clubbable:latest
