#!/bin/bash

if [ -z "$TARGET_ENV" ]
then
    echo Source environment variables using
    echo "    \$ source docker/env/<your target environment>"
    exit 2
fi

git archive --format=tar.gz --prefix=clubbable/ HEAD > clubbable.tar.gz
src/clubbable/manage.py collectstatic --noinput --settings clubbable.settings.$TARGET_ENV
cat docker/templates/clubbable.conf | docker/render-env.py > docker/nginx/conf.d/clubbable.conf
docker-compose build --build-arg target=$TARGET_ENV
rm -f clubbable.tar.gz
