#!/bin/bash

VERSION=`date +%Y.%m.%d.%H.%M.%S`

# Build docker image, tag and push
#docker/build-prod-image

# Build Elastic Beanstalk artifact
#docker/build-eb-artifact

echo "Deploying clubbable-eb.zip to clubbable-env with label v.$VERSION"
eb deploy --label=v.$VERSION --staged clubbable-env
