#!/bin/bash

VERSION=`date +%Y.%m.%d.%H.%M.%S`

echo "Deploying clubbable to $TARGET_ENV with label v.$VERSION"
sleep 1
echo -n .
sleep 1
echo -n .
sleep 1
echo .

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -i|--build-image)
        # Build docker image, tag and push
        docker/build-image
        shift
        ;;
        -a|--build-artifact)
        # Build Elastic Beanstalk artifact
        docker/build-eb-artifact
        shift
        ;;
    esac
done

eb deploy --label=v.$VERSION --staged clubbable-env
