#!/bin/bash

rm -rf docker/nginx/secrets/*
eb ssh -c 'cd /var/app/current && sudo tar -cf - docker/nginx/secrets/' | tar -xf -

# Expect the following error when "tar -c" completes:
#   Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
#   BrokenPipeError: [Errno 32] Broken pipe
