# Generated by Django 2.2.6 on 2020-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('banner_img_url', models.CharField(max_length=255)),
                ('content_markdown', models.TextField()),
                ('content_html', models.TextField()),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
