# Generated by Django 2.1.4 on 2018-12-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dropbox_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
