# Generated by Django 2.1.4 on 2018-12-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropboxer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxuser',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dropboxuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
