# Generated by Django 2.1.4 on 2018-12-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropboxer', '0002_auto_20181221_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxuser',
            name='cursor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
